/*Insert into the category table*/
INSERT INTO `the_cocktail_db`.`category`
VALUES
(null,'Ordinary Drink'),
(null,'Cocktail'),
(null,'Shake'),
(null,'Other'),
(null,'Unknown'),
(null,'Cocoa'),
(null,'Shot'),
(null,'Coffee'),
(null,'Tea'),
(null,'Homemade Liqueur'),
(null,'Punch'),
(null,'Party Drink'),
(null,'Beer'),
(null,'Soft Drink');

/*Insert into the glass table*/
INSERT INTO `the_cocktail_db`.`glass`
VALUES
(null,'Highball glass'),
(null,'Cocktail glass'),
(null,'Old-fashioned glass'),
(null,'Whiskey Glass'),
(null,'Collins glass'),
(null,'Pousse cafe glass'),
(null,'Champagne flute'),
(null,'Whiskey sour glass'),
(null,'Cordial glass'),
(null,'Brandy snifter'),
(null,'White wine glass'),
(null,'Nick and Nora Glass'),
(null,'Hurricane glass'),
(null,'Coffee mug'),
(null,'Shot glass'),
(null,'Jar'),
(null,'Irish coffee cup'),
(null,'Punch bowl'),
(null,'Pitcher'),
(null,'Pint glass'),
(null,'Copper Mug'),
(null,'Wine Glass'),
(null,'Beer mug'),
(null,'Margarita'),
(null,'Coupette glass'),
(null,'Beer pilsner'),
(null,'Beer Glass'),
(null,'Parfait glass'),
(null,'Mason jar'),
(null,'Margarita glass'),
(null,'Martini Glass'),
(null,'Balloon Glass'),
(null,'Coupe Glass');
